// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuGUzMvO86HmO1e-sgiGUaUrtVYsc3abo',
    appId: '1:94277441736:web:00915c52be1213b842edfd',
    messagingSenderId: '94277441736',
    projectId: 'nexoraai',
    authDomain: 'nexoraai.firebaseapp.com',
    storageBucket: 'nexoraai.firebasestorage.app',
    measurementId: 'G-014MTLEHNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjkzDScCAhkRbtoV7GFiuQZ_3jvsDvNc',
    appId: '1:94277441736:android:662db5469251f7ad42edfd',
    messagingSenderId: '94277441736',
    projectId: 'nexoraai',
    storageBucket: 'nexoraai.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuGUzMvO86HmO1e-sgiGUaUrtVYsc3abo',
    appId: '1:94277441736:web:41b893d08ff8e9cb42edfd',
    messagingSenderId: '94277441736',
    projectId: 'nexoraai',
    authDomain: 'nexoraai.firebaseapp.com',
    storageBucket: 'nexoraai.firebasestorage.app',
    measurementId: 'G-EC9WJT3K7D',
  );
}
